<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TweeServerLessSession\Module'                                        => __DIR__ . '/Module.php',
    'TweeServerLessSession\Session\Crypter'                               => __DIR__ . '/src/TweeServerLessSession/Session/Crypter.php',
    'TweeServerLessSession\Session\CrypterInterface'                      => __DIR__ . '/src/TweeServerLessSession/Session/CrypterInterface.php',
    'TweeServerLessSession\Session\Factory\ContainerFactory'              => __DIR__ . '/src/TweeServerLessSession/Session/Factory/ContainerFactory.php',
    'TweeServerLessSession\Session\Factory\CrypterFactory'                => __DIR__ . '/src/TweeServerLessSession/Session/Factory/CrypterFactory.php',
    'TweeServerLessSession\Session\Factory\SessionManagerFactory'         => __DIR__ . '/src/TweeServerLessSession/Session/Factory/SessionManagerFactory.php',
    'TweeServerLessSession\Session\SaveHandler\Factory\ServerLessFactory' => __DIR__ . '/src/TweeServerLessSession/Session/SaveHandler/Factory/ServerLessFactory.php',
    'TweeServerLessSession\Session\SaveHandler\StorageLess'               => __DIR__ . '/src/TweeServerLessSession/Session/SaveHandler/ServerLess.php',
);
